version: 0.0.0.{build}
os: Visual Studio 2015

install:
# Use the install script to grab the latest dotnet install
- ps: iex .\build\dotnet-latest.ps1

# Prepend newly installed dotnet cli to the PATH of this build (this cannot be
# done from inside the powershell script as it would require to restart
# the parent CMD process).
- "SET PATH=C:\\Program Files\\dotnet\\bin;%PATH%"

build_script:
- cmd: build.cmd

artifacts:
- path: artifacts\**\*.nupkg